baseURL = "https://phplemos.dev/"
title = "phplemos.dev"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 6

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Pedro Lemos"
description = "Pedro Lemos's personal blog"
keywords = "blog,developer,personal,fullstack,mobile"
info = ["Full Stack Mobile Developer", "GNU/Linux Enthusiast"]
avatarURL = "images/avatar.jpg" # User should replace this with their own avatar image
dateFormat = "January 2, 2006"
since = 2023 # Assuming the blog started recently
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/phplemos/" # Placeholder, user should update

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/phplemos/" # Placeholder, user should update

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"
