baseURL = "https://phplemos.dev/"
title = "phplemos.dev"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 6

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Pedro Henrique Pinheiro Lemos"
description = "A place to test my awareness about some areas of Computer Science and share my ideas."
keywords = "blog,personal,technology,programming,software development,linux,open source"
info = ["FullStack Mobile Developer", "I use arch btw :|", "One thing is one thing, another thing is another thing","Oxe?!, baiano can speak other language??"]
avatarURL = "images/phplemos.png"
dateFormat = "January 2, 2006"
since = 2026 # Assuming the blog started recently
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/phplemos/" # Placeholder, user should update

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/phplemos/" # Placeholder, user should update

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Curriculum Vitae"
weight = 4
url = "curriculum/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"
